## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: GitHub Discussions
    url: https://github.com/visibleai/visibleai/discussions
    about: For questions and discussions that don't belong in issues, please use our Discussions forum.